apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-iris-todo-deployment
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector: 
    matchLabels: 
      app: django-iris-todo-pod
  template: 
    metadata: 
      labels: 
        app: django-iris-todo-pod
    spec: 
    #   imagePullSecrets:
    #   {{- if .Values.requiredSecrets.intersystemsContainerRegistrySecret }}    
    #   - name: {{ .Values.requiredSecrets.intersystemsContainerRegistrySecret }}
    #   {{- end }}

      containers:
      - name: django-iris-todo-container
        {{- if eq .Values.skaffold.enabled true }}
        image: {{ .Values.skaffold.image }}
        {{- else }}
        image: {{ .Values.image.registry }}/{{ .Values.image.repository }}:{{ .Chart.AppVersion }}
        {{- end }}

        env:
        - name: IRIS_JDBC_URL
          value: {{ .Values.jdbcConnectionString }}
        - name: IRIS_USERNAME
          value: {{ .Values.irisUserName}}
        - name: IRIS_PASSWORD
          value: {{ .Values.irisPassword }}

        resources:
          requests:
            cpu: {{ .Values.compute.main.cpu }}
            memory: {{ .Values.compute.main.memory }}

      {{- if .Values.compute.main.nodeTypeSelector }}
      nodeSelector:
        sds/node-type: {{ .Values.compute.main.nodeTypeSelector }}
      {{- end }}
      tolerations:
      - key: sds/select-worker
        value: select-worker
        effect: NoSchedule

